WARNING ! 
JANGAN HAPUS/EDIT FILE INJ KARENA AKAN MENYEBABKAN EROR 

SC BY skyzo v5 recode by @verlangid

join grup kebutuhan hosting?
https://s.id/VCLOUDX
TESTI
https://t.me/alltestiverlangid


GW DOAIN YANG MEMPEJUAL BELIKAN SC INI YATIM PIATU
KARENA GW NIAT MEMBAGIKAN DENGAN FREE BIAR KALIAN BISA PAKE SC BAGUS ,DAN SE ENAKNY KALIAN JUAL
